#!/bin/sh

set -e

: "${S3_BUCKET:?Please set S3_BUCKET to the destination bucket (for instance, 'overview-multi-search')}"
: "${AWS_ACCESS_KEY_ID:?Please set AWS_ACCESS_KEY_ID}"
: "${AWS_SECRET_ACCESS_KEY:?Please set AWS_SECRET_ACCESS_KEY}"

DIR="$(dirname "$0")"

EXTRA_DOCKER_RUN_ARGS="-e S3_BUCKET=${S3_BUCKET} -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
exec "$DIR"/in-docker gulp deploy
